### ISSUE TITLE
SpreadsheetBean

### ISSUE THREAD

**Issue by dmkov** [Dezurat/SampleSpreadsheet#7]
Я не дуже побачив ідею, але можливо я просто не знаю про такий підхід. Яка користь в використанні SpreadsheetBean додатково з моделлю/сервісом? Візуально це виглядає як зайвий компонент, який треба тягнути за собою в контролері - https://screencast.com/t/WRUS5bJwhSbH

В другому випадку об'єкт створюється за допомогою конструктора з spreadsheet, а в першому - через setters, що виглядає не дуже послідовно

**Comment by Dezurat** [comment]
в першому випадку, коли через сетери, мені потрібно взяти тільки id та name, якими будуть заповнюватись селекти на сторінці, щоб не передавати на сторінку відповідь з цілою таблицею (в нашому випадку 10 на 10).
